### ISSUE TITLE
dmp_startapp breaks with django v 1.10

### ISSUE THREAD

**Issue by JasonSmithIS** [doconix/django-mako-plus#19]
DMP requirements state that django 1.8+ are compatible, but after upgrading to 1.10 I get the following error message when I try to start a new DMP app.

(Input) $ python manage.py dmp_startapp homepage
(Output) WARNING Sass integration not enabled.
usage: manage.py dmp_startapp [-h] [--version] [-v {0,1,2,3}]
                              [--settings SETTINGS] [--pythonpath PYTHONPATH]
                              [--traceback] [--no-color]
manage.py dmp_startapp: error: unrecognized arguments: homepage

**Comment by doconix** [comment]
Jason --

I haven't upgraded DMP to 1.10 yet.  I'll do so now and test it to be sure everything works.  For the moment, you could downgrade Django to 1.9 (pip install django==1.9).  I should have a fix up shortly.

**Comment by doconix** [comment]
It should all be upgraded.  All you need to do is `pip3 install --upgrade django-mako-plus`

I'll continue to test and post any updates as needed.
