### ISSUE TITLE
How to pass the mako variable or python variable  to a  js function ?

### ISSUE THREAD

**Issue by b1322457** [doconix/django-mako-plus#2]
I am looking the source code of the hue and  what to do some change.I noticed  that  in the .mako file ,It contains javascript and out side of the js we can use the mako syntax and get the variable in  the context,but I want to use it in the js function.I don't know how to get it,I think it can be geted,so i asked the way.

**Comment by doconix** [comment]
I'm not sure I understand your issue very well, so a code example might be useful.  You should be able to do mako code directly within Javascript without any problems.  If the JS is within your .mako file, it should just work.

If the JS is separated out (the way the DMP tutorial describes) into a different file, be sure it is named file.jsm (with a .jsm extension) and not with .js.  When DMP sees .jsm, it renders the file through the Mako engine.
