### ISSUE TITLE
User Set Database Variables

### ISSUE THREAD

**Issue by palanjam** [doconix/django-mako-plus#22]
This isn't an issue for DMP but maybe Django itself (or my inability in this area). What is the recommended practice for storing settings that would be set by the user but would apply to the entire app? For example, lets say an app I'm running should be displayed in a particular theme, a set time zone, or default values that would populate fields within the app. My original thought was to create a 'settings' model but that seems counterintuitive since the database won't ever have more than the one value that will be set on the settings page. The other idea, which I've used for other programming languages, is to create a settings.cfg file of some sort on the system and parse the file. But again, this seems a little clunky to me on DMP. What do you suggest @doconix?

**Comment by doconix** [comment]
I'm closing the issue because it's been a long time.  Sorry I missed this question.  Please repost if you want to discuss more.
