### ISSUE TITLE
Django @csrf_exempt doesn't work

### ISSUE THREAD

**Issue by ngoue** [doconix/django-mako-plus#33]
The way routing works with DMP prevents Django's `@csrf_exempt` (and probably a myriad of other decorators) from functioning correctly.  DMP doesn't actually give the decorated view function back to the `CsrfViewMiddleware` – instead it's getting the DMP `route_request` function and so it never gets the `@csrf_exempt` check to pass.

**Comment by doconix** [comment]
This is fixed in the newest version.  It is an entire refactor of the way route_request gets called.  It now is a `resolver` instead of an endpoint.  So the real endpoint function is a first-order endpoint to Django -- making all decorators work as expected.

**Comment by doconix** [comment]
Let me know if you have any issues with this in the new version.
