### ISSUE TITLE
Broken link to default app and page

### ISSUE THREAD

**Issue by palanjam** [doconix/django-mako-plus#35]
I'm trying to set my app as the default so it doesn't need to be typed but can't get to the page that describes it since the link is broken, both on github and readthedocs. 

https://github.com/doconix/django-mako-plus/blob/master/docs/tutorial_meet_dmp.rst

**Comment by doconix** [comment]
Thanks. This is fixed in the docs.  

To put the answer here as well, you need to set `DEFAULT_APP` and/or `DEFAULT_PAGE` in your settings. See here: https://django-mako-plus.readthedocs.io/basics_settings.html
