### ISSUE TITLE
Templating System doesn't play nice with projects like social-auth-app-django

### ISSUE THREAD

**Issue by madamson8** [doconix/django-mako-plus#36]
social-auth-app-django is a project that is commonly used to simplify social authentication with sites like Twitter and Facebook.  Using the system they currently have, authentication is handled by sending users to a url such as `<a href="{% url 'social:begin' 'facebook' %}">Sign up</a>`.

DMP converts the templating language so this isn't recognized.  Looking at [this page](https://django-mako-plus.readthedocs.io/about.html#comparison-with-django) of the documentation, it looks like we should be able to get around this by changing the above code to `<a href="<% url 'social:begin' 'facebook' %>`.

One possible solution I'm looking into is using regex to ignore certain urls from loading with the DMP engine:

urls.py:

```
urlpatterns = [
    # the built-in Django administrator
    url(r'^admin/', admin.site.urls),

    # urls for any third-party apps go here
    url('oauth/', include('social_django.urls', namespace='social')),

    # the DMP router - this should normally be the last URL listed
    re_path(r'^(?!(oauth.*)$).+$', include('django_mako_plus.urls')), <-- This is modified
]
```

The problem with this is that it changes the number of view arguments called which causes the page to display an error.

Is there another way around this?

**Comment by doconix** [comment]
There's a couple of things to note:

1. I don't think it's an issue with the number of view arguments. I could be wrong, but I don't think that's the problem. I'd have to see your stack trace to know more on that.
2. The code you show `<% 'social:begin' %> isn't going to work. The `url` tag that Django uses is looking for a URL pattern name (in this case, defined in the `social_django.urls` file). It has to do with reversing urls. I think the correct code for DMP would be something like this:

```
<%! from django.urls import reverse %>

<a href="${ reverse('social:begin') }">
```
I haven't tried it myself, but the reverse function in Django looks up URLs by name. I think that's what you are trying to do here.

**Comment by doconix** [comment]
Sorry didn't mean to close it. Feel free to respond.
