### ISSUE TITLE
dmp_collectstatic creates empty static folder

### ISSUE THREAD

**Issue by EnochLucas** [doconix/django-mako-plus#38]
Hey,

First I just want to say that I've been using this framework for over 2 years and I absolutely love it. Recently I came across an issue with dmp_collectstatic. After running python manage.py dmp_collectstatic it creates an empty static folder(without any of the css, js, html or any other folders). Not sure exactly what is causing this issue. Just thought I'd bring it to your attention.

Thanks again for making such a spectacular package for Django.

**Comment by doconix** [comment]
Thanks for the feedback! I think I fixed this recently in the new version. I'll do a double check.

Closing this issue, but feel free to reopen it if you still have issues with the current release.
