### ISSUE TITLE
"ImportError: cannot import name 'get_renderer'" in tutorial

### ISSUE THREAD

**Issue by seanfisher** [doconix/django-mako-plus#4]
The line in the readme tutorial in the file `homepage/views/index.py` gives me an error:
`ImportError: cannot import name 'get_renderer'`

By changing it to
`from django_mako_plus.controller import view_function, router`

and then changing
`templater = get_renderer('homepage')`
to
`templater = router.get_renderer('homepage')`

the error goes away and everything works fine.

**Comment by SecretSighter** [comment]
Or you can say from django_mako_plus.controller.router import get_renderer on a new line. The README needs to be updated.

**Comment by doconix** [comment]
Done!  Readme is updated.
