### ISSUE TITLE
Django in a subdirectory

### ISSUE THREAD

**Issue by stratosgear** [doconix/django-mako-plus#7]
I have install my django app in a subdirectory like:

    my.domain.com/devSite

and when I hit my application running in:

    my.domain.com/devSite/timesheets/index

I see that django-mako-plus is interpreting the path incorrectly. I get:

    [Mon Mar 16 16:05:08.744563 2015] [:error] [pid 31279:tid 140465995564800] DEBUG DMP :: processing: app=homepage, page=devSite, func=process_request, urlparams=[u'timesheets', u'index']                                                                                                                                   
    [Mon Mar 16 16:05:08.748229 2015] [:error] [pid 31279:tid 140465995564800] DEBUG DMP :: module homepage.views.devSite not found; sending processing directly to template devSite.html                                                                                                                                       
    [Mon Mar 16 16:05:08.748460 2015] [:error] [pid 31279:tid 140465995564800] DEBUG DMP :: App homepage is not a designated DMP app.  Template rendering is not possible without DJANGO_MAKO_PLUS=True in its __init__.py file.                                                                                                

while I was expecting to read something like:

    processing: app=timesheets, page=index, func=process_request, urlparams=[]   

How can I inform django-mako-plus to start reading after my subdirectory...?

[edit]:  Just to clarify, that the app in the local development server is working fine.  Only during my production install (through WSGI) I get that error, when I try to run it from a subdirectory.

Thanks!

**Comment by kvngard** [comment]
Could you post the code where you're trying to reach the URL? I've noticed that within my application, I always need to explicitly state the URL as '/app/view.viewfunction/urlparameters/.' You'll notice that, because you've used a string in the app portion of the URL that your project doesn't recognize ('devSite'), the DMP router has defaulted to the default app that you've listed in your settings.py file ('homepage'). 

Just as a side note, the default app and default page are set using the DMP_DEFAULT_PAGE, DMP_DEFAULT_APP options in your settings file. The DMP router will default to these if it doesn't recognize something in your URL.

**Comment by doconix** [comment]
DMP doesn’t really support having your entire site in a subdirectory — devSite/ in your case.  It’s going to see the first url part as the app (devSite) and the second part as the .py file to call (timesheets).  In your URL, “index” is request.urlparams[0]

I have no problem adding this behavior to DMP, though.  It just doesn’t do this now.

-- 
Conan C. Albrecht, Ph.D.
Information Systems Department
Brigham Young University
Email: ca@byu.edu
Blog: http://goalbrecht.com/

**Comment by stratosgear** [comment]
I just think that having the site hosted in a subdirectory makes sense, so I consider this a valuable fix if you can indeed implement it.

Thanks!

**Comment by doconix** [comment]
Sure. Will do asap. Hopefully in the next couple days.

**Comment by doconix** [comment]
I just uploaded a change that makes it possible to have a subdirectory.  See the tutorial here:

https://github.com/doconix/django-mako-plus#installing-django-in-a-subdirectory

And be sure to update DMP:

pip install --upgrade django-mako-plus

Let me know if you have any bugs with it.  

Once you upgrade, all you should have to do is add "DMP_URL_START_INDEX=0" to settings.py.  Note that I switched the way the settings.py items are specified, so the tutorial will be a little different than what you already have.  You can switch to the new format or use DMP_URL_START_INDEX with the old format.

-- 
Conan C. Albrecht, Ph.D.
Information Systems Department
Brigham Young University
Email: ca@byu.edu
Blog: http://goalbrecht.com/

**Comment by stratosgear** [comment]
You're the man! :) Thanks!
