### ISSUE TITLE
Werkzeug debugger broken

### ISSUE THREAD

**Issue by psilar** [doconix/django-mako-plus#9]
When I use django-mako-plus, I lost the Werkzeug debugger functionality (using runserver_plus).  It seems that DMP is outputting the page without passing it to Werkzeug.  Is there some setting that I've missed?

**Comment by psilar** [comment]
This issue seems to have been related to the context processors not being run, which has been resolved in push-request #12.  Could you please generate a new release (2.4.10) so that these fixes are picked up in a pip install?

**Comment by doconix** [comment]
Yes, will do now.

-- 
Conan C. Albrecht, Ph.D.
Information Systems Department
Brigham Young University
ca@byu.edu
KG7USZ
http://goalbrecht.com/
